MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  CLS_AGNOSTIC_BBOX_REG: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 12000 #2000
    PRE_NMS_TOP_N_TEST: 6000 #1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    BATCH_SIZE_PER_IMAGE: 256
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictorCascade"
    NUM_CLASSES: 12
    USE_CASCADE: True
    IOU_PRED: False
DATASETS:
  TRAIN: ("coco_visdrone_train",)
  TEST: ("coco_visdrone_valid",)
  TRANSTYPE: 'transforms2d'
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01 #0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (2500, 2750, 7500) #(60000, 80000)
  MAX_ITER: 10000 #90000
  IMS_PER_BATCH: 8
  TEST_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 16
OUTPUT_DIR: './outputs/visdrone/cascade_rcnn/'
